spring:
  application:
    name: webflux-test
  r2dbc:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    properties:
      schema: ${POSTGRES_SCHEMA}
    

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
server:
  port: ${SERVER_PORT}

jwk:
  private:
    key: ${JWK_LOCATION}/${JWK_PRIVATE_PEM}
  public:
    key: ${JWK_LOCATION}/${JWK_PUBLIC_PEM}